Repository Cappua/cappua-fe, pull requests merged in 2021-03, with the labels that each got.

#48 Sort bug fixed in TrackCard
  src/features/TrackCards/TrackCards.js
  src/features/User/User.js
Labels: Sprint2, bug, frontend

#51 Login user query added to User component
  src/GraphQL/mutations.js
  src/GraphQL/queries.js
  src/features/User/User.js
Labels: Sprint2, enhancement, frontend

#52 Display votes
  src/App.css
  src/App.js
  src/GraphQL/queries.js
  src/Utilities/logo.jpg
  src/assets/_sampleData/sampeUserData.js
  src/assets/_sampleData/trioData.js
  src/assets/dylon.mp3
  src/assets/uploadIcon.png
  src/assets/wu_tang.jpg
  src/features/AlbumCard/AlbumCard.js
  src/features/AnimatedArrows/AnimatedArrows.js
  src/features/Announcement/Announcement.css
  src/features/Announcement/Announcement.js
  src/features/AudioPlayer/AudioPlayer.js
  src/features/AudioPlayer/audioPlayer.css
  src/features/Banner/Banner.css
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/Competition/Competition.css
  src/features/Competition/Competition.js
  src/features/Error/Error.css
  src/features/Error/Error.js
  src/features/FirstPlace/FirstPlace.css
  src/features/FirstPlace/FirstPlace.js
  src/features/NavBar/NavBar.css
  src/features/NavBar/NavBar.js
  src/features/Olympus/Olympus.js
  src/features/Olympus/Olympus.scss
  src/features/SoundWave/SoundWave.css
  src/features/SoundWave/SoundWave.js
  src/features/Theme/Theme.js
  src/features/TrackCards/TrackCards.css
  src/features/TrackNav/TrackNav.css
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
  src/features/Winners/Winners.css
  src/features/Winners/Winners.js
  src/index.js
Labels: enhancement, frontend

#53 Feature/user voting functionality
  src/App.js
  src/GraphQL/mutations.js
  src/GraphQL/queries.js
  src/MonthContext.js
  src/features/AudioPlayer/AudioPlayer.js
  src/features/Competition/Competition.js
  src/features/TrackCards/TrackCards.js
  src/features/Upvote/Upvote.css
  src/features/Upvote/Upvote.js
  src/features/User/User.css
  src/features/User/User.js
Labels: Sprint2, enhancement, frontend

#58 Bug/upload track
  src/GraphQL/queries.js
  src/features/AudioPlayer/Song.js
  src/features/Competition/Competition.js
  src/features/Theme/Theme.css
  src/features/Theme/Theme.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackNav/TrackNav.js
  src/features/UploadTrack/UploadMessage.js
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
Labels: Sprint2, enhancement, frontend

#57 Cypress Testing & Lighthouse Accessibility rating
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/features/AlbumCard.spec.js
  cypress/integration/features/AudioPlayer.spec.js
  cypress/integration/features/Banner.spec.js
  cypress/integration/features/Body.spec.js
  cypress/integration/features/Competition.spec.js
  cypress/integration/features/FirstPlace.spec.js
  cypress/integration/features/Loading.spec.js
  cypress/integration/features/NavBar.spec.js
  cypress/integration/features/Olympus.spec.js
  cypress/integration/features/Theme.spec.js
  cypress/integration/features/TrackCards.spec.js
  cypress/integration/features/TrackNav.spec.js
  cypress/integration/features/Trio.spec.js
  cypress/integration/features/UploadTrack.spec.js
  cypress/integration/features/User.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App.js
  src/features/AnimatedArrows/AnimatedArrows.js
  src/features/AnimatedArrows/AnimatedArrows.scss
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/Error/Error.js
  src/features/FirstPlace/FirstPlace.css
  src/features/InstrumentalsArtwork/InstrumentalArtwork.css
  src/features/InstrumentalsArtwork/InstrumentalArtwork.js
  src/features/NavBar/NavBar.js
  src/features/Olympus/Olympus.js
  src/features/Olympus/Olympus.scss
  src/features/TrackCards/TrackCards.js
  src/features/Trio/Trio.js
  src/features/Winners/Winners.css
  src/features/Winners/Winners.js
Labels: enhancement, frontend

#59 Aws fix
  cypress/integration/features/TrackNav.spec.js
  cypress/integration/features/UploadTrack.spec.js
  src/App.js
Labels: bug

#61 Cypress/testing
  cypress.json
  cypress/integration/features/AlbumCard.spec.js
  cypress/integration/features/AudioPlayer.spec.js
  cypress/integration/features/Banner.spec.js
  cypress/integration/features/NavBar.spec.js
  cypress/integration/features/Theme.spec.js
  cypress/integration/features/Trio.spec.js
  cypress/integration/features/UploadTrack.spec.js
  cypress/integration/features/User.spec.js
  src/features/User/User.js
Labels: Sprint2, enhancement, frontend

#62 Bug vote
  src/App.js
  src/features/Announcement/Announcement.css
  src/features/Announcement/Announcement.js
  src/features/AudioPlayer/Song.js
  src/features/Upvote/Upvote.js
Labels: Sprint2, bug, enhancement

#64 Backend endpoints updated and posting correctly
  src/ApolloClient/apolloClient.js
  src/features/UploadTrack/UploadTrack.js
Labels: Sprint2, documentation, enhancement

#65 bug fix auth0
  src/index.js
Labels: bug

#66 Added redirect with heroku deployment
  src/index.js
Labels: bug

#67 heroku deployment fix
  cypress/integration/features/AudioPlayer.spec.js
  cypress/integration/features/Banner.spec.js
  cypress/integration/features/NavBar.spec.js
  cypress/integration/features/Trio.spec.js
  cypress/integration/features/User.spec.js
  src/App.js
Labels: bug

#68 Responsive design
  src/features/AudioPlayer/audioPlayer.css
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/FirstPlace/FirstPlace.css
  src/features/NavBar/NavBar.css
  src/features/NavBar/NavBar.js
  src/features/Olympus/Olympus.scss
  src/features/TrackCards/TrackCards.css
  src/features/TrackCards/TrackCards.js
  src/features/Trio/Trio.css
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
  src/features/Winners/Winners.css
Labels: frontend

#69 Responsive design & Bug Fix
  src/features/AudioPlayer/audioPlayer.css
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/FirstPlace/FirstPlace.css
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/features/Winners/Winners.css
  src/features/Winners/Winners.js
Labels: bug, enhancement

#70 Aws endpoints working
  src/ApolloClient/apolloClient.js
  src/features/UploadTrack/UploadTrack.js
Labels: Sprint2, enhancement, frontend

#71 back to heroku end points for https
  src/ApolloClient/apolloClient.js
  src/features/UploadTrack/UploadTrack.js
Labels: bug
