Repository Cappua/cappua-fe, pull requests merged in 2021-02, with the labels that each got.

#2 Setup
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
  public/manifest.json
  src/App.css
  src/App.js
  src/Utilities/logo.jpg
  src/Utilities/trioData.js
  src/features/Announcement/Announcement.css
  src/features/Announcement/Announcement.js
  src/features/Banner/Banner.css
  src/features/Banner/Banner.js
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/Login/Login.css
  src/features/Login/Login.js
  src/features/NavBar/NavBar.css
  src/features/NavBar/NavBar.js
  src/features/SoundBar/SoundBar.css
  src/features/SoundBar/SoundBar.js
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/index.css
Labels: enhancement, frontend

#10 Setup
  package-lock.json
  package.json
  src/App.js
  src/Utilities/trioData.js
  src/assets/cappualogo.png
  src/features/NavBar/NavBar.js
  src/features/TrackCard/TrackCard.css
  src/features/TrackCard/TrackCard.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackNav/TrackNav.js
  src/features/Tracktitle/TrackTitle.css
  src/features/Tracktitle/TrackTitle.js
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/features/User/User.css
  src/features/User/User.js
  src/index.js
Labels: Sprint 1

#14 User Login && Responsive Design
  src/App.js
  src/features/Announcement/Announcement.css
  src/features/Announcement/Announcement.js
  src/features/Banner/Banner.css
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/NavBar/NavBar.css
  src/features/NavBar/NavBar.js
  src/features/SoundBar/SoundBar.css
  src/features/SoundBar/SoundBar.js
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/features/User/User.css
  src/features/User/User.js
  src/index.css
  src/index.js
Labels: enhancement, frontend

#15 Feature/track pages
  src/App.js
  src/assets/_sampleData/mad_villan.png
  src/assets/_sampleData/sampleUser1.jpg
  src/assets/_sampleData/sampleUser2.jpg
  src/assets/_sampleData/sampleUser3.jpg
  src/assets/searchIcon.png
  src/assets/uploadIcon.png
  src/assets/wu_tang.jpg
  src/features/InstrumentalsArtwork/InstrumentalArtwork.css
  src/features/InstrumentalsArtwork/InstrumentalArtwork.js
  src/features/NavBar/NavBar.css
  src/features/NavBar/NavBar.js
  src/features/TrackCard/TrackCard.css
  src/features/TrackCard/TrackCard.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackNav/TrackNav.js
  src/features/TrackPage/TrackPage.css
  src/features/TrackPage/TrackPage.js
  src/features/Tracktitle/TrackTitle.js
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
  src/features/User/User.css
Labels: Sprint 1

#21 Track page styling
  package-lock.json
  package.json
  src/features/AlbumCard/AlbumCard.css
  src/features/AlbumCard/AlbumCard.js
  src/features/AudioPlayer/AudioPlayer.js
  src/features/AudioPlayer/audioPlayer.css
  src/features/TrackCard/TrackCard.css
  src/features/TrackCard/TrackCard.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackNav/TrackNav.js
  src/features/TrackPage/TrackPage.css
  src/features/TrackPage/TrackPage.js
Labels: MVP, Sprint 1, frontend

#22 Feature/file upload 2
  package-lock.json
  package.json
  src/assets/_sampleData/sampeUserData.js
  src/features/AlbumCard/AlbumCard.css
  src/features/AlbumCard/AlbumCard.js
  src/features/AudioPlayer/audioPlayer.css
  src/features/TrackCard/TrackCard.css
  src/features/TrackCard/TrackCard.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackPage/TrackPage.js
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
Labels: MVP, Sprint 1, enhancement, frontend

#23 Add buildspec.yml for CodePipeline
  buildspec.yml
Labels: Sprint2, enhancement, frontend

#24 Fix typo in buildspec.yml file
  buildspec.yml
Labels: bug

#25 Bug fix npm install in yml file
  buildspec.yml
Labels: Sprint2, bug, frontend

#26 Add one passing test to app test for AWS deployment
  src/App.test.js
Labels: Sprint2, bug, frontend

#27 Bug fix for AWS deployment updated run build and removed test
  buildspec.yml
Labels: Sprint2, bug

#28 Trackpage
  public/manifest.json
  src/App.js
  src/assets/_sampleData/mad_villan.png
  src/assets/_sampleData/sampeUserData.js
  src/assets/_sampleData/sampleUser1.jpg
  src/assets/_sampleData/sampleUser2.jpg
  src/assets/_sampleData/sampleUser3.jpg
  src/assets/searchIcon.png
  src/features/AlbumCard/AlbumCard.css
  src/features/AlbumCard/AlbumCard.js
  src/features/Announcement/Announcement.css
  src/features/AudioPlayer/AudioPlayer.js
  src/features/Body/Body.css
  src/features/Login/Login.css
  src/features/Login/Login.js
  src/features/NavBar/NavBar.css
  src/features/SoundBar/SoundBar.css
  src/features/SoundBar/SoundBar.js
  src/features/Theme/Theme.css
  src/features/Theme/Theme.js
  src/features/TrackCard/TrackCard.css
  src/features/TrackCard/TrackCard.js
  src/features/TrackPage/TrackPage.css
  src/features/TrackPage/TrackPage.js
  src/features/Trio/Trio.css
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
  src/index.js
  src/logo.svg
  src/serviceWorker.js
  src/setupTests.js
Labels: enhancement, frontend

#29 Create Winner & Theme components
  src/App.js
  src/app/store.js
  src/assets/_sampleData/sampeUserData.js
  src/features/AlbumCard/AlbumCard.js
  src/features/Theme/Theme.css
  src/features/Theme/Theme.js
  src/features/TrackCard/TrackCard.css
  src/features/TrackCard/TrackCard.js
  src/features/TrackNav/TrackNav.css
  src/features/UploadTrack/UploadTrack.css
  src/features/Winners/Winners.js
  src/features/Winners/Winners.scss
Labels: enhancement, frontend

#31 Track card queries
  package-lock.json
  package.json
  src/ApolloClient/apolloClient.js
  src/App.js
  src/GraphQL/mutations.js
  src/GraphQL/queries.js
  src/features/TrackCard/TrackCard.js
  src/features/TrackCards/TrackCards.css
  src/features/TrackCards/TrackCards.js
  src/features/TrackPage/TrackPage.js
  src/features/UploadTrack/UploadTrack.js
  src/index.js
Labels: Sprint2, enhancement, frontend

#37 Winners display
  README.md
  src/App.css
  src/assets/_sampleData/sampeUserData.js
  src/assets/_sampleData/trioData.js
  src/features/AlbumCard/AlbumCard.css
  src/features/AudioPlayer/AudioPlayer.js
  src/features/AudioPlayer/audioPlayer.css
  src/features/Body/Body.js
  src/features/FirstPlace/FirstPlace.css
  src/features/FirstPlace/FirstPlace.js
  src/features/Theme/Theme.css
  src/features/Theme/Theme.js
  src/features/TrackCards/TrackCards.css
  src/features/TrackCards/TrackCards.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackPage/TrackPage.css
  src/features/TrackPage/TrackPage.js
  src/features/Trio/Trio.css
  src/features/Trio/Trio.js
  src/features/UploadTrack/UploadTrack.css
  src/features/UploadTrack/UploadTrack.js
  src/features/Winners/Winners.css
  src/features/Winners/Winners.js
  src/features/Winners/Winners.scss
Labels: enhancement, frontend

#38 Feature/track card queries update
  src/App.js
  src/CompetitionContext.js
  src/GraphQL/queries.js
  src/features/AlbumCard/AlbumCard.css
  src/features/AlbumCard/AlbumCard.js
  src/features/AudioPlayer/AudioPlayer.js
  src/features/Error/Error.css
  src/features/Error/Error.js
  src/features/Loading/Loading.css
  src/features/Loading/Loading.js
  src/features/TrackCards/TrackCards.js
  src/index.js
Labels: MVP, Sprint2, enhancement, frontend

#44 Restyling
  src/App.js
  src/assets/_sampleData/sampeUserData.js
  src/features/AlbumCard/AlbumCard.css
  src/features/AlbumCard/AlbumCard.js
  src/features/AnimatedArrows/AnimatedArrows.js
  src/features/AnimatedArrows/AnimatedArrows.scss
  src/features/Competition/Competition.css
  src/features/Competition/Competition.js
  src/features/FirstPlace/FirstPlace.css
  src/features/FirstPlace/FirstPlace.js
  src/features/Loading/Loading.css
  src/features/Loading/Loading.js
  src/features/NavBar/NavBar.js
  src/features/TrackCards/TrackCards.css
  src/features/TrackCards/TrackCards.js
  src/features/TrackNav/TrackNav.css
  src/features/TrackNav/TrackNav.js
  src/features/Trio/Trio.css
  src/features/UploadTrack/UploadTrack.css
  src/features/Winners/Winners.css
  src/features/Winners/Winners.js
Labels: enhancement, frontend

#45 Olympus
  src/App.js
  src/assets/_sampleData/sampeUserData.js
  src/features/Body/Body.css
  src/features/Body/Body.js
  src/features/NavBar/NavBar.js
  src/features/Olympus/Olympus.js
  src/features/Olympus/Olympus.scss
  src/features/SoundWave/SoundWave.css
  src/features/SoundWave/SoundWave.js
  src/features/Theme/Theme.js
  src/features/TrackCards/TrackCards.css
  src/features/TrackCards/TrackCards.js
  src/features/UploadTrack/UploadTrack.js
  src/features/Winners/Winners.css
  src/features/Winners/Winners.js
  src/index.js
Labels: enhancement, frontend

#46 Feature/user functionality
  .env
  src/App.js
  src/UserContext.js
  src/features/AlbumCard/AlbumCard.css
  src/features/AlbumCard/AlbumCard.js
  src/features/Banner/Banner.css
  src/features/Competition/Competition.js
  src/features/Loading/Loading.js
  src/features/NavBar/NavBar.css
  src/features/NavBar/NavBar.js
  src/features/TrackCards/TrackCards.js
  src/features/User/User.css
  src/features/User/User.js
  src/features/Winners/Winners.js
  src/index.js
Labels: Sprint2, enhancement, frontend
